### ISSUE TITLE
The front page is too dark and too close

### ISSUE THREAD

**Issue by meekrosoft** [Praqma/praqma.github.io#53] opened 2015-11-11 19:31 UTC
All the pictures are dark and you have to zoom out to make sense of the page.  My 2cents, but its how I feel.

**Comment by lakruzz** [comment] 2015-11-11 19:49
@meekrosoft 

> All the pictures 

Does that mean:

- [ ] on the front page?
- [ ] in general = literally _all_ pictures?

> you have to zoom out to make sense of the page

So what you say is that it's simply to large! it should be more dense?

I tend to agree on that! - I zoom out to about 75% and that seems to be just about the proportions that feels right.

**Comment by meekrosoft** [comment] 2015-11-11 19:54
On the zoom level: yes, I think it is too large.  It is hard on the eyes and confusing because you don't land in an understandable context.  At default zoom level I have no idea what I'm looking at.  Does that make sense?

**Comment by lakruzz** [comment] 2015-11-11 20:03
Yep!

## On the topic of the pictures

The ones we have here are sample images, we will have to address the issue of the quality of the images being used, page-by-page when we're narrowing in and start focusing on content.

**Comment by lakruzz** [comment] 2015-11-11 20:11
Closing this one as a duplicate of #54

**Closed by lakruzz** 2015-11-11 20:11 UTC
Labels: Duplicate
