### ISSUE TITLE
Filtering on story tags with spaces in them redirect to a 404 page

### ISSUE THREAD

**Issue by praqma-thi** [Praqma/praqma.github.io#146] opened 2016-01-21 06:54 UTC
Clicking on a tag to filter blog posts redirects to a 404 page when it has a space in it.
e.g. www.praqma.com/stories/#Job DSL

Happens on Firefox 43.0 (Linux)

**Comment by lakruzz** [comment] 2016-01-21 08:32
Duplicate of #134

**Closed** 2016-01-21 08:32 UTC
Labels: Prio 2 - should have, Status - duplicate
